services:
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
    # - ./server:/workspace
    - ./data:/workspace/data
    - /workspace/node_modules
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./server 
          target: /workspace
          action: sync
        - path: ./server/package.json
          action: rebuild

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes: 
    # - ./client:/workspace
    - /workspace/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - server
    develop:
      watch:
        - path: ./client 
          target: /workspace
          action: sync
        - path: ./client/package.json
          action: rebuild
